
# Command to run playbook : ansible-playbook  quark_agent_ansible.yml --extra-vars='ansible_sudo_pass=harish'

---
- name: Verify quark agent proper
  hosts: localhost
  remote_user: harish
  port: 2229
  become: sudo
  tasks:
        - name: Transfer script
          copy: src=agent_checker.sh dest=~ mode=0777

        - name: Execute the script 
          command: sh ~/agent_checker.sh
          register: agent_checker.sh

        - name: Grep log file 
          chdir: '/var/log/neutron'
          command: 'cat quark-agent.log | grep -i error'
          register: grep_output

        - debug:
            var: grep_output.stdout_lines
          
          
