
# Command to run playbook : ansible-playbook  quark_agent_ansible.yml --extra-vars='ansible_sudo_pass=harish' -v 

---
- name: Verify quark agent proper
  hosts: localhost
  remote_user: harish
  port: 2229
  become: sudo
  tasks:
             

        - name: Grep log file 
          command: cat /var/log/neutron/quark-agent.log | grep ERROR
          register: grep_output
          ignore_errors: true

        - debug:
            var:
              grep_output.stdout_lines

        - name: A task which happens only when some log line is present
          when: grep_output.stdout_lines[{{item}}].find('wifi') !=-1
          with_items: 
            -  grep_output.stdout_lines[{{item}}]
          debug: msg="quark agent alert log found"
          loop:
            - 0
            - 1
            - 2
            - 3


        # Three things to be done, 1. replace the hardcoded error with ignore and include
        # 2. replace the with item with generic iteration.



        #with:
        #    grep_output.stdout_lines
            #when: 
            #  grep_output.stdout_lines ! = '';
            


